# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\deviceAssigningTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.seggerText = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seggerText.sizePolicy().hasHeightForWidth())
        self.seggerText.setSizePolicy(sizePolicy)
        self.seggerText.setMaximumSize(QtCore.QSize(180, 117))
        self.seggerText.setText("")
        self.seggerText.setPixmap(QtGui.QPixmap(".\\img/SEGGER-Logo-the-embedded-experts-RGB.png"))
        self.seggerText.setScaledContents(True)
        self.seggerText.setAlignment(QtCore.Qt.AlignCenter)
        self.seggerText.setObjectName("seggerText")
        self.verticalLayout_6.addWidget(self.seggerText, 0, QtCore.Qt.AlignHCenter)
        self.powerOnButton = QtWidgets.QPushButton(self.groupBox)
        self.powerOnButton.setStyleSheet("QAbstractButton {\n"
"    font-size: 16pt\n"
"}")
        self.powerOnButton.setObjectName("powerOnButton")
        self.verticalLayout_6.addWidget(self.powerOnButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hexFilesLabel = QtWidgets.QLabel(self.groupBox)
        self.hexFilesLabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.hexFilesLabel.setObjectName("hexFilesLabel")
        self.horizontalLayout_2.addWidget(self.hexFilesLabel, 0, QtCore.Qt.AlignBottom)
        self.flashStatusLabel = QtWidgets.QLabel(self.groupBox)
        self.flashStatusLabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.flashStatusLabel.setObjectName("flashStatusLabel")
        self.horizontalLayout_2.addWidget(self.flashStatusLabel, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.hexFileComboBox = QtWidgets.QComboBox(self.groupBox)
        self.hexFileComboBox.setStyleSheet("QComboBox {\n"
"    font-size: 10pt\n"
"}\n"
"")
        self.hexFileComboBox.setObjectName("hexFileComboBox")
        self.verticalLayout_6.addWidget(self.hexFileComboBox)
        self.flashButton = QtWidgets.QPushButton(self.groupBox)
        self.flashButton.setStyleSheet("QAbstractButton {\n"
"    font-size: 16pt\n"
"}")
        self.flashButton.setObjectName("flashButton")
        self.verticalLayout_6.addWidget(self.flashButton)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.devicesForPrintLabel = QtWidgets.QLabel(self.groupBox)
        self.devicesForPrintLabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.devicesForPrintLabel.setObjectName("devicesForPrintLabel")
        self.verticalLayout_8.addWidget(self.devicesForPrintLabel)
        self.devicesForPrintTableView = QtWidgets.QTableView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesForPrintTableView.sizePolicy().hasHeightForWidth())
        self.devicesForPrintTableView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.devicesForPrintTableView.setFont(font)
        self.devicesForPrintTableView.setObjectName("devicesForPrintTableView")
        self.verticalLayout_8.addWidget(self.devicesForPrintTableView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.readMacButton = QtWidgets.QPushButton(self.groupBox)
        self.readMacButton.setStyleSheet("QAbstractButton {\n"
"    font-size: 10pt\n"
"}")
        self.readMacButton.setObjectName("readMacButton")
        self.horizontalLayout_3.addWidget(self.readMacButton)
        self.addDeviceButton = QtWidgets.QPushButton(self.groupBox)
        self.addDeviceButton.setStyleSheet("QAbstractButton {\n"
"    font-size: 10pt\n"
"}")
        self.addDeviceButton.setObjectName("addDeviceButton")
        self.horizontalLayout_3.addWidget(self.addDeviceButton)
        self.printNowButton = QtWidgets.QPushButton(self.groupBox)
        self.printNowButton.setStyleSheet("QAbstractButton {\n"
"    font-size: 10pt\n"
"}")
        self.printNowButton.setObjectName("printNowButton")
        self.horizontalLayout_3.addWidget(self.printNowButton)
        self.clearListButton = QtWidgets.QPushButton(self.groupBox)
        self.clearListButton.setStyleSheet("QAbstractButton {\n"
"    font-size: 10pt\n"
"}")
        self.clearListButton.setObjectName("clearListButton")
        self.horizontalLayout_3.addWidget(self.clearListButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.deviceTypeLabel = QtWidgets.QLabel(self.groupBox)
        self.deviceTypeLabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.deviceTypeLabel.setObjectName("deviceTypeLabel")
        self.verticalLayout_7.addWidget(self.deviceTypeLabel)
        self.deviceTypeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.deviceTypeComboBox.setStyleSheet("QComboBox {\n"
"    font-size: 10pt\n"
"}")
        self.deviceTypeComboBox.setObjectName("deviceTypeComboBox")
        self.verticalLayout_7.addWidget(self.deviceTypeComboBox)
        self.deviceNameLabel = QtWidgets.QLabel(self.groupBox)
        self.deviceNameLabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.deviceNameLabel.setObjectName("deviceNameLabel")
        self.verticalLayout_7.addWidget(self.deviceNameLabel)
        self.deviceNameComboBox = QtWidgets.QComboBox(self.groupBox)
        self.deviceNameComboBox.setStyleSheet("QComboBox {\n"
"    font-size: 10pt\n"
"}")
        self.deviceNameComboBox.setObjectName("deviceNameComboBox")
        self.verticalLayout_7.addWidget(self.deviceNameComboBox)
        self.locationLabel = QtWidgets.QLabel(self.groupBox)
        self.locationLabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.locationLabel.setObjectName("locationLabel")
        self.verticalLayout_7.addWidget(self.locationLabel)
        self.locationComboBox = QtWidgets.QComboBox(self.groupBox)
        self.locationComboBox.setStyleSheet("QComboBox {\n"
"    font-size: 10pt\n"
"}")
        self.locationComboBox.setObjectName("locationComboBox")
        self.verticalLayout_7.addWidget(self.locationComboBox)
        self.controllerTypeLabel = QtWidgets.QLabel(self.groupBox)
        self.controllerTypeLabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.controllerTypeLabel.setObjectName("controllerTypeLabel")
        self.verticalLayout_7.addWidget(self.controllerTypeLabel)
        self.controllerTypeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.controllerTypeComboBox.setStyleSheet("QComboBox {\n"
"    font-size: 10pt\n"
"}\n"
"")
        self.controllerTypeComboBox.setObjectName("controllerTypeComboBox")
        self.verticalLayout_7.addWidget(self.controllerTypeComboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.macIDLabel = QtWidgets.QLabel(self.groupBox)
        self.macIDLabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.macIDLabel.setObjectName("macIDLabel")
        self.horizontalLayout.addWidget(self.macIDLabel)
        self.macStatuslabel = QtWidgets.QLabel(self.groupBox)
        self.macStatuslabel.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.macStatuslabel.setObjectName("macStatuslabel")
        self.horizontalLayout.addWidget(self.macStatuslabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.macIDShowLabel = QtWidgets.QLabel(self.groupBox)
        self.macIDShowLabel.setText("")
        self.macIDShowLabel.setObjectName("macIDShowLabel")
        self.verticalLayout_7.addWidget(self.macIDShowLabel, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 320))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SQLLiteConsole = QtWidgets.QLabel(self.groupBox_2)
        self.SQLLiteConsole.setStyleSheet("QLabel {\n"
"    font-size: 10pt\n"
"}")
        self.SQLLiteConsole.setObjectName("SQLLiteConsole")
        self.verticalLayout_2.addWidget(self.SQLLiteConsole)
        self.devicesDBTableView = QtWidgets.QTableView(self.groupBox_2)
        self.devicesDBTableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.devicesDBTableView.setFont(font)
        self.devicesDBTableView.setObjectName("devicesDBTableView")
        self.verticalLayout_2.addWidget(self.devicesDBTableView)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Console"))
        self.powerOnButton.setText(_translate("MainWindow", "PowerOn"))
        self.hexFilesLabel.setText(_translate("MainWindow", "Choose Your Hex Files"))
        self.flashStatusLabel.setText(_translate("MainWindow", "Flash Status : None"))
        self.flashButton.setText(_translate("MainWindow", "Flash!"))
        self.devicesForPrintLabel.setText(_translate("MainWindow", "Devices For Label Printing (max 3 device)"))
        self.readMacButton.setText(_translate("MainWindow", "Read Mac"))
        self.addDeviceButton.setText(_translate("MainWindow", "Add Device"))
        self.printNowButton.setText(_translate("MainWindow", "Print Now!"))
        self.clearListButton.setText(_translate("MainWindow", "Clear List"))
        self.deviceTypeLabel.setText(_translate("MainWindow", "Device Type"))
        self.deviceNameLabel.setText(_translate("MainWindow", "Device Name"))
        self.locationLabel.setText(_translate("MainWindow", "Location"))
        self.controllerTypeLabel.setText(_translate("MainWindow", "Controller Type"))
        self.macIDLabel.setText(_translate("MainWindow", "MAC ID :"))
        self.macStatuslabel.setText(_translate("MainWindow", "Read Mac Status : None"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Database"))
        self.SQLLiteConsole.setText(_translate("MainWindow", "SQL Lite"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
